# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dbms.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dbms.proto',
  package='com.gftchina.common.persistence.dbms',
  serialized_pb=_b('\n\ndbms.proto\x12$com.gftchina.common.persistence.dbms\"5\n\x08OneField\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0c\n\x04type\x18\x02 \x02(\x05\x12\r\n\x02io\x18\x03 \x01(\x05:\x01\x30\"P\n\x0e\x44ocumentFields\x12>\n\x06\x66ields\x18\x01 \x03(\x0b\x32..com.gftchina.common.persistence.dbms.OneField\"\xb7\x03\n\x0e\x46ieldCondition\x12=\n\x05\x66ield\x18\x01 \x01(\x0b\x32..com.gftchina.common.persistence.dbms.OneField\x12O\n\x04oset\x18\x02 \x01(\x0b\x32?.com.gftchina.common.persistence.dbms.FieldCondition.StringListH\x00\x12J\n\x01i\x18\x03 \x01(\x0b\x32=.com.gftchina.common.persistence.dbms.FieldCondition.IntRangeH\x00\x12M\n\x01v\x18\x04 \x01(\x0b\x32@.com.gftchina.common.persistence.dbms.FieldCondition.DoubleRangeH\x00\x1a\x1e\n\nStringList\x12\x10\n\x08\x65lements\x18\x01 \x03(\t\x1a$\n\x08IntRange\x12\x0b\n\x03min\x18\x01 \x01(\x05\x12\x0b\n\x03max\x18\x02 \x01(\x05\x1a\'\n\x0b\x44oubleRange\x12\x0b\n\x03min\x18\x01 \x01(\x01\x12\x0b\n\x03max\x18\x02 \x01(\x01\x42\x0b\n\tcondition')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ONEFIELD = _descriptor.Descriptor(
  name='OneField',
  full_name='com.gftchina.common.persistence.dbms.OneField',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='com.gftchina.common.persistence.dbms.OneField.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='com.gftchina.common.persistence.dbms.OneField.type', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='io', full_name='com.gftchina.common.persistence.dbms.OneField.io', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=105,
)


_DOCUMENTFIELDS = _descriptor.Descriptor(
  name='DocumentFields',
  full_name='com.gftchina.common.persistence.dbms.DocumentFields',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fields', full_name='com.gftchina.common.persistence.dbms.DocumentFields.fields', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=187,
)


_FIELDCONDITION_STRINGLIST = _descriptor.Descriptor(
  name='StringList',
  full_name='com.gftchina.common.persistence.dbms.FieldCondition.StringList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='elements', full_name='com.gftchina.common.persistence.dbms.FieldCondition.StringList.elements', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=507,
  serialized_end=537,
)

_FIELDCONDITION_INTRANGE = _descriptor.Descriptor(
  name='IntRange',
  full_name='com.gftchina.common.persistence.dbms.FieldCondition.IntRange',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='min', full_name='com.gftchina.common.persistence.dbms.FieldCondition.IntRange.min', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max', full_name='com.gftchina.common.persistence.dbms.FieldCondition.IntRange.max', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=539,
  serialized_end=575,
)

_FIELDCONDITION_DOUBLERANGE = _descriptor.Descriptor(
  name='DoubleRange',
  full_name='com.gftchina.common.persistence.dbms.FieldCondition.DoubleRange',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='min', full_name='com.gftchina.common.persistence.dbms.FieldCondition.DoubleRange.min', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max', full_name='com.gftchina.common.persistence.dbms.FieldCondition.DoubleRange.max', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=577,
  serialized_end=616,
)

_FIELDCONDITION = _descriptor.Descriptor(
  name='FieldCondition',
  full_name='com.gftchina.common.persistence.dbms.FieldCondition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='field', full_name='com.gftchina.common.persistence.dbms.FieldCondition.field', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='oset', full_name='com.gftchina.common.persistence.dbms.FieldCondition.oset', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='i', full_name='com.gftchina.common.persistence.dbms.FieldCondition.i', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='v', full_name='com.gftchina.common.persistence.dbms.FieldCondition.v', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_FIELDCONDITION_STRINGLIST, _FIELDCONDITION_INTRANGE, _FIELDCONDITION_DOUBLERANGE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='condition', full_name='com.gftchina.common.persistence.dbms.FieldCondition.condition',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=190,
  serialized_end=629,
)

_DOCUMENTFIELDS.fields_by_name['fields'].message_type = _ONEFIELD
_FIELDCONDITION_STRINGLIST.containing_type = _FIELDCONDITION
_FIELDCONDITION_INTRANGE.containing_type = _FIELDCONDITION
_FIELDCONDITION_DOUBLERANGE.containing_type = _FIELDCONDITION
_FIELDCONDITION.fields_by_name['field'].message_type = _ONEFIELD
_FIELDCONDITION.fields_by_name['oset'].message_type = _FIELDCONDITION_STRINGLIST
_FIELDCONDITION.fields_by_name['i'].message_type = _FIELDCONDITION_INTRANGE
_FIELDCONDITION.fields_by_name['v'].message_type = _FIELDCONDITION_DOUBLERANGE
_FIELDCONDITION.oneofs_by_name['condition'].fields.append(
  _FIELDCONDITION.fields_by_name['oset'])
_FIELDCONDITION.fields_by_name['oset'].containing_oneof = _FIELDCONDITION.oneofs_by_name['condition']
_FIELDCONDITION.oneofs_by_name['condition'].fields.append(
  _FIELDCONDITION.fields_by_name['i'])
_FIELDCONDITION.fields_by_name['i'].containing_oneof = _FIELDCONDITION.oneofs_by_name['condition']
_FIELDCONDITION.oneofs_by_name['condition'].fields.append(
  _FIELDCONDITION.fields_by_name['v'])
_FIELDCONDITION.fields_by_name['v'].containing_oneof = _FIELDCONDITION.oneofs_by_name['condition']
DESCRIPTOR.message_types_by_name['OneField'] = _ONEFIELD
DESCRIPTOR.message_types_by_name['DocumentFields'] = _DOCUMENTFIELDS
DESCRIPTOR.message_types_by_name['FieldCondition'] = _FIELDCONDITION

OneField = _reflection.GeneratedProtocolMessageType('OneField', (_message.Message,), dict(
  DESCRIPTOR = _ONEFIELD,
  __module__ = 'dbms_pb2'
  # @@protoc_insertion_point(class_scope:com.gftchina.common.persistence.dbms.OneField)
  ))
_sym_db.RegisterMessage(OneField)

DocumentFields = _reflection.GeneratedProtocolMessageType('DocumentFields', (_message.Message,), dict(
  DESCRIPTOR = _DOCUMENTFIELDS,
  __module__ = 'dbms_pb2'
  # @@protoc_insertion_point(class_scope:com.gftchina.common.persistence.dbms.DocumentFields)
  ))
_sym_db.RegisterMessage(DocumentFields)

FieldCondition = _reflection.GeneratedProtocolMessageType('FieldCondition', (_message.Message,), dict(

  StringList = _reflection.GeneratedProtocolMessageType('StringList', (_message.Message,), dict(
    DESCRIPTOR = _FIELDCONDITION_STRINGLIST,
    __module__ = 'dbms_pb2'
    # @@protoc_insertion_point(class_scope:com.gftchina.common.persistence.dbms.FieldCondition.StringList)
    ))
  ,

  IntRange = _reflection.GeneratedProtocolMessageType('IntRange', (_message.Message,), dict(
    DESCRIPTOR = _FIELDCONDITION_INTRANGE,
    __module__ = 'dbms_pb2'
    # @@protoc_insertion_point(class_scope:com.gftchina.common.persistence.dbms.FieldCondition.IntRange)
    ))
  ,

  DoubleRange = _reflection.GeneratedProtocolMessageType('DoubleRange', (_message.Message,), dict(
    DESCRIPTOR = _FIELDCONDITION_DOUBLERANGE,
    __module__ = 'dbms_pb2'
    # @@protoc_insertion_point(class_scope:com.gftchina.common.persistence.dbms.FieldCondition.DoubleRange)
    ))
  ,
  DESCRIPTOR = _FIELDCONDITION,
  __module__ = 'dbms_pb2'
  # @@protoc_insertion_point(class_scope:com.gftchina.common.persistence.dbms.FieldCondition)
  ))
_sym_db.RegisterMessage(FieldCondition)
_sym_db.RegisterMessage(FieldCondition.StringList)
_sym_db.RegisterMessage(FieldCondition.IntRange)
_sym_db.RegisterMessage(FieldCondition.DoubleRange)


# @@protoc_insertion_point(module_scope)
