# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fiQuery.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fiQuery.proto',
  package='com.gftchina.common.fiQuery',
  serialized_pb=_b('\n\rfiQuery.proto\x12\x1b\x63om.gftchina.common.fiQuery\"7\n\x05\x46ield\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0c\n\x04type\x18\x02 \x02(\x05\x12\x12\n\x07inOrOut\x18\x03 \x01(\x05:\x01\x30\"D\n\x0e\x44ocumentFields\x12\x32\n\x06\x66ields\x18\x01 \x03(\x0b\x32\".com.gftchina.common.fiQuery.Field\"\x90\x03\n\x0e\x46ieldCondition\x12\x31\n\x05\x66ield\x18\x01 \x01(\x0b\x32\".com.gftchina.common.fiQuery.Field\x12\x46\n\x04oset\x18\x02 \x01(\x0b\x32\x36.com.gftchina.common.fiQuery.FieldCondition.StringListH\x00\x12\x41\n\x01i\x18\x03 \x01(\x0b\x32\x34.com.gftchina.common.fiQuery.FieldCondition.IntRangeH\x00\x12\x44\n\x01v\x18\x04 \x01(\x0b\x32\x37.com.gftchina.common.fiQuery.FieldCondition.DoubleRangeH\x00\x1a\x1e\n\nStringList\x12\x10\n\x08\x65lements\x18\x01 \x03(\t\x1a$\n\x08IntRange\x12\x0b\n\x03min\x18\x01 \x01(\x05\x12\x0b\n\x03max\x18\x02 \x01(\x05\x1a\'\n\x0b\x44oubleRange\x12\x0b\n\x03min\x18\x01 \x01(\x01\x12\x0b\n\x03max\x18\x02 \x01(\x01\x42\x0b\n\tcondition\"\"\n\x13QueryFIRecordSchema\x12\x0b\n\x03gid\x18\x01 \x02(\t\"D\n\x0e\x46IRecordSchema\x12\x32\n\x06\x66ields\x18\x01 \x03(\x0b\x32\".com.gftchina.common.fiQuery.Field\"\xee\x01\n\x0eQueryFIRecords\x12?\n\nconditions\x18\x01 \x03(\x0b\x32+.com.gftchina.common.fiQuery.FieldCondition\x12\x10\n\x05limit\x18\x02 \x01(\r:\x01\x31\x12\x35\n\tselection\x18\x03 \x03(\x0b\x32\".com.gftchina.common.fiQuery.Field\x12\x12\n\nsessionGid\x18\x04 \x01(\t\x12\x11\n\taggregate\x18\x05 \x01(\x08\x12\x11\n\tqueryData\x18\x06 \x01(\x08\x12\x18\n\x10\x61ggreationChoice\x18\x07 \x01(\x05\"q\n\x14\x43lientQueryFIRecords\x12\x1a\n\x12jsonFiQueryRequest\x18\x01 \x02(\t\x12\x11\n\tfiInstGid\x18\x02 \x02(\t\x12\x10\n\x08\x66qDefGid\x18\x03 \x02(\t\x12\x18\n\x10\x61ggreationChoice\x18\x04 \x01(\x05*I\n\x0f\x41ggregationType\x12\t\n\x05\x43ount\x10\x01\x12\x07\n\x03Max\x10\x02\x12\x07\n\x03Min\x10\x04\x12\x07\n\x03\x41vg\x10\x08\x12\x07\n\x03Sum\x10\x10\x12\x07\n\x03\x41ll\x10\x1f')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_AGGREGATIONTYPE = _descriptor.EnumDescriptor(
  name='AggregationType',
  full_name='com.gftchina.common.fiQuery.AggregationType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Count', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Max', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Min', index=2, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Avg', index=3, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Sum', index=4, number=16,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='All', index=5, number=31,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=1038,
  serialized_end=1111,
)
_sym_db.RegisterEnumDescriptor(_AGGREGATIONTYPE)

AggregationType = enum_type_wrapper.EnumTypeWrapper(_AGGREGATIONTYPE)
Count = 1
Max = 2
Min = 4
Avg = 8
Sum = 16
All = 31



_FIELD = _descriptor.Descriptor(
  name='Field',
  full_name='com.gftchina.common.fiQuery.Field',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='com.gftchina.common.fiQuery.Field.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='com.gftchina.common.fiQuery.Field.type', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='inOrOut', full_name='com.gftchina.common.fiQuery.Field.inOrOut', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=101,
)


_DOCUMENTFIELDS = _descriptor.Descriptor(
  name='DocumentFields',
  full_name='com.gftchina.common.fiQuery.DocumentFields',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fields', full_name='com.gftchina.common.fiQuery.DocumentFields.fields', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=171,
)


_FIELDCONDITION_STRINGLIST = _descriptor.Descriptor(
  name='StringList',
  full_name='com.gftchina.common.fiQuery.FieldCondition.StringList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='elements', full_name='com.gftchina.common.fiQuery.FieldCondition.StringList.elements', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=452,
  serialized_end=482,
)

_FIELDCONDITION_INTRANGE = _descriptor.Descriptor(
  name='IntRange',
  full_name='com.gftchina.common.fiQuery.FieldCondition.IntRange',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='min', full_name='com.gftchina.common.fiQuery.FieldCondition.IntRange.min', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max', full_name='com.gftchina.common.fiQuery.FieldCondition.IntRange.max', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=484,
  serialized_end=520,
)

_FIELDCONDITION_DOUBLERANGE = _descriptor.Descriptor(
  name='DoubleRange',
  full_name='com.gftchina.common.fiQuery.FieldCondition.DoubleRange',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='min', full_name='com.gftchina.common.fiQuery.FieldCondition.DoubleRange.min', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max', full_name='com.gftchina.common.fiQuery.FieldCondition.DoubleRange.max', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=522,
  serialized_end=561,
)

_FIELDCONDITION = _descriptor.Descriptor(
  name='FieldCondition',
  full_name='com.gftchina.common.fiQuery.FieldCondition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='field', full_name='com.gftchina.common.fiQuery.FieldCondition.field', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='oset', full_name='com.gftchina.common.fiQuery.FieldCondition.oset', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='i', full_name='com.gftchina.common.fiQuery.FieldCondition.i', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='v', full_name='com.gftchina.common.fiQuery.FieldCondition.v', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_FIELDCONDITION_STRINGLIST, _FIELDCONDITION_INTRANGE, _FIELDCONDITION_DOUBLERANGE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='condition', full_name='com.gftchina.common.fiQuery.FieldCondition.condition',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=174,
  serialized_end=574,
)


_QUERYFIRECORDSCHEMA = _descriptor.Descriptor(
  name='QueryFIRecordSchema',
  full_name='com.gftchina.common.fiQuery.QueryFIRecordSchema',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gid', full_name='com.gftchina.common.fiQuery.QueryFIRecordSchema.gid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=576,
  serialized_end=610,
)


_FIRECORDSCHEMA = _descriptor.Descriptor(
  name='FIRecordSchema',
  full_name='com.gftchina.common.fiQuery.FIRecordSchema',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fields', full_name='com.gftchina.common.fiQuery.FIRecordSchema.fields', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=612,
  serialized_end=680,
)


_QUERYFIRECORDS = _descriptor.Descriptor(
  name='QueryFIRecords',
  full_name='com.gftchina.common.fiQuery.QueryFIRecords',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='conditions', full_name='com.gftchina.common.fiQuery.QueryFIRecords.conditions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='limit', full_name='com.gftchina.common.fiQuery.QueryFIRecords.limit', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='selection', full_name='com.gftchina.common.fiQuery.QueryFIRecords.selection', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sessionGid', full_name='com.gftchina.common.fiQuery.QueryFIRecords.sessionGid', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='aggregate', full_name='com.gftchina.common.fiQuery.QueryFIRecords.aggregate', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='queryData', full_name='com.gftchina.common.fiQuery.QueryFIRecords.queryData', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='aggreationChoice', full_name='com.gftchina.common.fiQuery.QueryFIRecords.aggreationChoice', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=683,
  serialized_end=921,
)


_CLIENTQUERYFIRECORDS = _descriptor.Descriptor(
  name='ClientQueryFIRecords',
  full_name='com.gftchina.common.fiQuery.ClientQueryFIRecords',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='jsonFiQueryRequest', full_name='com.gftchina.common.fiQuery.ClientQueryFIRecords.jsonFiQueryRequest', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fiInstGid', full_name='com.gftchina.common.fiQuery.ClientQueryFIRecords.fiInstGid', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fqDefGid', full_name='com.gftchina.common.fiQuery.ClientQueryFIRecords.fqDefGid', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='aggreationChoice', full_name='com.gftchina.common.fiQuery.ClientQueryFIRecords.aggreationChoice', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=923,
  serialized_end=1036,
)

_DOCUMENTFIELDS.fields_by_name['fields'].message_type = _FIELD
_FIELDCONDITION_STRINGLIST.containing_type = _FIELDCONDITION
_FIELDCONDITION_INTRANGE.containing_type = _FIELDCONDITION
_FIELDCONDITION_DOUBLERANGE.containing_type = _FIELDCONDITION
_FIELDCONDITION.fields_by_name['field'].message_type = _FIELD
_FIELDCONDITION.fields_by_name['oset'].message_type = _FIELDCONDITION_STRINGLIST
_FIELDCONDITION.fields_by_name['i'].message_type = _FIELDCONDITION_INTRANGE
_FIELDCONDITION.fields_by_name['v'].message_type = _FIELDCONDITION_DOUBLERANGE
_FIELDCONDITION.oneofs_by_name['condition'].fields.append(
  _FIELDCONDITION.fields_by_name['oset'])
_FIELDCONDITION.fields_by_name['oset'].containing_oneof = _FIELDCONDITION.oneofs_by_name['condition']
_FIELDCONDITION.oneofs_by_name['condition'].fields.append(
  _FIELDCONDITION.fields_by_name['i'])
_FIELDCONDITION.fields_by_name['i'].containing_oneof = _FIELDCONDITION.oneofs_by_name['condition']
_FIELDCONDITION.oneofs_by_name['condition'].fields.append(
  _FIELDCONDITION.fields_by_name['v'])
_FIELDCONDITION.fields_by_name['v'].containing_oneof = _FIELDCONDITION.oneofs_by_name['condition']
_FIRECORDSCHEMA.fields_by_name['fields'].message_type = _FIELD
_QUERYFIRECORDS.fields_by_name['conditions'].message_type = _FIELDCONDITION
_QUERYFIRECORDS.fields_by_name['selection'].message_type = _FIELD
DESCRIPTOR.message_types_by_name['Field'] = _FIELD
DESCRIPTOR.message_types_by_name['DocumentFields'] = _DOCUMENTFIELDS
DESCRIPTOR.message_types_by_name['FieldCondition'] = _FIELDCONDITION
DESCRIPTOR.message_types_by_name['QueryFIRecordSchema'] = _QUERYFIRECORDSCHEMA
DESCRIPTOR.message_types_by_name['FIRecordSchema'] = _FIRECORDSCHEMA
DESCRIPTOR.message_types_by_name['QueryFIRecords'] = _QUERYFIRECORDS
DESCRIPTOR.message_types_by_name['ClientQueryFIRecords'] = _CLIENTQUERYFIRECORDS
DESCRIPTOR.enum_types_by_name['AggregationType'] = _AGGREGATIONTYPE

Field = _reflection.GeneratedProtocolMessageType('Field', (_message.Message,), dict(
  DESCRIPTOR = _FIELD,
  __module__ = 'fiQuery_pb2'
  # @@protoc_insertion_point(class_scope:com.gftchina.common.fiQuery.Field)
  ))
_sym_db.RegisterMessage(Field)

DocumentFields = _reflection.GeneratedProtocolMessageType('DocumentFields', (_message.Message,), dict(
  DESCRIPTOR = _DOCUMENTFIELDS,
  __module__ = 'fiQuery_pb2'
  # @@protoc_insertion_point(class_scope:com.gftchina.common.fiQuery.DocumentFields)
  ))
_sym_db.RegisterMessage(DocumentFields)

FieldCondition = _reflection.GeneratedProtocolMessageType('FieldCondition', (_message.Message,), dict(

  StringList = _reflection.GeneratedProtocolMessageType('StringList', (_message.Message,), dict(
    DESCRIPTOR = _FIELDCONDITION_STRINGLIST,
    __module__ = 'fiQuery_pb2'
    # @@protoc_insertion_point(class_scope:com.gftchina.common.fiQuery.FieldCondition.StringList)
    ))
  ,

  IntRange = _reflection.GeneratedProtocolMessageType('IntRange', (_message.Message,), dict(
    DESCRIPTOR = _FIELDCONDITION_INTRANGE,
    __module__ = 'fiQuery_pb2'
    # @@protoc_insertion_point(class_scope:com.gftchina.common.fiQuery.FieldCondition.IntRange)
    ))
  ,

  DoubleRange = _reflection.GeneratedProtocolMessageType('DoubleRange', (_message.Message,), dict(
    DESCRIPTOR = _FIELDCONDITION_DOUBLERANGE,
    __module__ = 'fiQuery_pb2'
    # @@protoc_insertion_point(class_scope:com.gftchina.common.fiQuery.FieldCondition.DoubleRange)
    ))
  ,
  DESCRIPTOR = _FIELDCONDITION,
  __module__ = 'fiQuery_pb2'
  # @@protoc_insertion_point(class_scope:com.gftchina.common.fiQuery.FieldCondition)
  ))
_sym_db.RegisterMessage(FieldCondition)
_sym_db.RegisterMessage(FieldCondition.StringList)
_sym_db.RegisterMessage(FieldCondition.IntRange)
_sym_db.RegisterMessage(FieldCondition.DoubleRange)

QueryFIRecordSchema = _reflection.GeneratedProtocolMessageType('QueryFIRecordSchema', (_message.Message,), dict(
  DESCRIPTOR = _QUERYFIRECORDSCHEMA,
  __module__ = 'fiQuery_pb2'
  # @@protoc_insertion_point(class_scope:com.gftchina.common.fiQuery.QueryFIRecordSchema)
  ))
_sym_db.RegisterMessage(QueryFIRecordSchema)

FIRecordSchema = _reflection.GeneratedProtocolMessageType('FIRecordSchema', (_message.Message,), dict(
  DESCRIPTOR = _FIRECORDSCHEMA,
  __module__ = 'fiQuery_pb2'
  # @@protoc_insertion_point(class_scope:com.gftchina.common.fiQuery.FIRecordSchema)
  ))
_sym_db.RegisterMessage(FIRecordSchema)

QueryFIRecords = _reflection.GeneratedProtocolMessageType('QueryFIRecords', (_message.Message,), dict(
  DESCRIPTOR = _QUERYFIRECORDS,
  __module__ = 'fiQuery_pb2'
  # @@protoc_insertion_point(class_scope:com.gftchina.common.fiQuery.QueryFIRecords)
  ))
_sym_db.RegisterMessage(QueryFIRecords)

ClientQueryFIRecords = _reflection.GeneratedProtocolMessageType('ClientQueryFIRecords', (_message.Message,), dict(
  DESCRIPTOR = _CLIENTQUERYFIRECORDS,
  __module__ = 'fiQuery_pb2'
  # @@protoc_insertion_point(class_scope:com.gftchina.common.fiQuery.ClientQueryFIRecords)
  ))
_sym_db.RegisterMessage(ClientQueryFIRecords)


# @@protoc_insertion_point(module_scope)
