# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hbaseTable.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hbaseTable.proto',
  package='com.gftchina.common.persistence.hbaseTable',
  serialized_pb=_b('\n\x10hbaseTable.proto\x12*com.gftchina.common.persistence.hbaseTable\"*\n\x0c\x42\x65ginEndPair\x12\r\n\x05\x62\x65gin\x18\x01 \x02(\x03\x12\x0b\n\x03\x65nd\x18\x02 \x02(\x03\"s\n\x0floadDataRequest\x12\x10\n\x08tableGid\x18\x01 \x02(\t\x12N\n\x0c\x62\x65ginEndDate\x18\x02 \x02(\x0b\x32\x38.com.gftchina.common.persistence.hbaseTable.BeginEndPair\"g\n\tTableMeta\x12\x14\n\x0c\x63olumn_names\x18\x01 \x03(\t\x12\r\n\x05oSize\x18\x02 \x02(\x05\x12\r\n\x05tSize\x18\x03 \x02(\x05\x12\r\n\x05vSize\x18\x04 \x02(\x05\x12\x17\n\x0fupdateTimestamp\x18\x05 \x02(\x03\"<\n\x06OneRow\x12\x11\n\ttimestamp\x18\x01 \x02(\x03\x12\t\n\x01o\x18\x02 \x03(\t\x12\t\n\x01t\x18\x03 \x03(\x03\x12\t\n\x01v\x18\x04 \x03(\x01\"\x93\x01\n\nHBaseTable\x12\x43\n\x04meta\x18\x01 \x02(\x0b\x32\x35.com.gftchina.common.persistence.hbaseTable.TableMeta\x12@\n\x04rows\x18\x02 \x03(\x0b\x32\x32.com.gftchina.common.persistence.hbaseTable.OneRow')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_BEGINENDPAIR = _descriptor.Descriptor(
  name='BeginEndPair',
  full_name='com.gftchina.common.persistence.hbaseTable.BeginEndPair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='begin', full_name='com.gftchina.common.persistence.hbaseTable.BeginEndPair.begin', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end', full_name='com.gftchina.common.persistence.hbaseTable.BeginEndPair.end', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=106,
)


_LOADDATAREQUEST = _descriptor.Descriptor(
  name='loadDataRequest',
  full_name='com.gftchina.common.persistence.hbaseTable.loadDataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tableGid', full_name='com.gftchina.common.persistence.hbaseTable.loadDataRequest.tableGid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='beginEndDate', full_name='com.gftchina.common.persistence.hbaseTable.loadDataRequest.beginEndDate', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=223,
)


_TABLEMETA = _descriptor.Descriptor(
  name='TableMeta',
  full_name='com.gftchina.common.persistence.hbaseTable.TableMeta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='column_names', full_name='com.gftchina.common.persistence.hbaseTable.TableMeta.column_names', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='oSize', full_name='com.gftchina.common.persistence.hbaseTable.TableMeta.oSize', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tSize', full_name='com.gftchina.common.persistence.hbaseTable.TableMeta.tSize', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vSize', full_name='com.gftchina.common.persistence.hbaseTable.TableMeta.vSize', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='updateTimestamp', full_name='com.gftchina.common.persistence.hbaseTable.TableMeta.updateTimestamp', index=4,
      number=5, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=225,
  serialized_end=328,
)


_ONEROW = _descriptor.Descriptor(
  name='OneRow',
  full_name='com.gftchina.common.persistence.hbaseTable.OneRow',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='com.gftchina.common.persistence.hbaseTable.OneRow.timestamp', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='o', full_name='com.gftchina.common.persistence.hbaseTable.OneRow.o', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='t', full_name='com.gftchina.common.persistence.hbaseTable.OneRow.t', index=2,
      number=3, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='v', full_name='com.gftchina.common.persistence.hbaseTable.OneRow.v', index=3,
      number=4, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=330,
  serialized_end=390,
)


_HBASETABLE = _descriptor.Descriptor(
  name='HBaseTable',
  full_name='com.gftchina.common.persistence.hbaseTable.HBaseTable',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='meta', full_name='com.gftchina.common.persistence.hbaseTable.HBaseTable.meta', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rows', full_name='com.gftchina.common.persistence.hbaseTable.HBaseTable.rows', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=393,
  serialized_end=540,
)

_LOADDATAREQUEST.fields_by_name['beginEndDate'].message_type = _BEGINENDPAIR
_HBASETABLE.fields_by_name['meta'].message_type = _TABLEMETA
_HBASETABLE.fields_by_name['rows'].message_type = _ONEROW
DESCRIPTOR.message_types_by_name['BeginEndPair'] = _BEGINENDPAIR
DESCRIPTOR.message_types_by_name['loadDataRequest'] = _LOADDATAREQUEST
DESCRIPTOR.message_types_by_name['TableMeta'] = _TABLEMETA
DESCRIPTOR.message_types_by_name['OneRow'] = _ONEROW
DESCRIPTOR.message_types_by_name['HBaseTable'] = _HBASETABLE

BeginEndPair = _reflection.GeneratedProtocolMessageType('BeginEndPair', (_message.Message,), dict(
  DESCRIPTOR = _BEGINENDPAIR,
  __module__ = 'hbaseTable_pb2'
  # @@protoc_insertion_point(class_scope:com.gftchina.common.persistence.hbaseTable.BeginEndPair)
  ))
_sym_db.RegisterMessage(BeginEndPair)

loadDataRequest = _reflection.GeneratedProtocolMessageType('loadDataRequest', (_message.Message,), dict(
  DESCRIPTOR = _LOADDATAREQUEST,
  __module__ = 'hbaseTable_pb2'
  # @@protoc_insertion_point(class_scope:com.gftchina.common.persistence.hbaseTable.loadDataRequest)
  ))
_sym_db.RegisterMessage(loadDataRequest)

TableMeta = _reflection.GeneratedProtocolMessageType('TableMeta', (_message.Message,), dict(
  DESCRIPTOR = _TABLEMETA,
  __module__ = 'hbaseTable_pb2'
  # @@protoc_insertion_point(class_scope:com.gftchina.common.persistence.hbaseTable.TableMeta)
  ))
_sym_db.RegisterMessage(TableMeta)

OneRow = _reflection.GeneratedProtocolMessageType('OneRow', (_message.Message,), dict(
  DESCRIPTOR = _ONEROW,
  __module__ = 'hbaseTable_pb2'
  # @@protoc_insertion_point(class_scope:com.gftchina.common.persistence.hbaseTable.OneRow)
  ))
_sym_db.RegisterMessage(OneRow)

HBaseTable = _reflection.GeneratedProtocolMessageType('HBaseTable', (_message.Message,), dict(
  DESCRIPTOR = _HBASETABLE,
  __module__ = 'hbaseTable_pb2'
  # @@protoc_insertion_point(class_scope:com.gftchina.common.persistence.hbaseTable.HBaseTable)
  ))
_sym_db.RegisterMessage(HBaseTable)


# @@protoc_insertion_point(module_scope)
