# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: idMapping.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='idMapping.proto',
  package='com.gftchina.common.calcProtocol.idMapping',
  serialized_pb=_b('\n\x0fidMapping.proto\x12*com.gftchina.common.calcProtocol.idMapping\"0\n\tDomainDef\x12\x0e\n\x06\x64omain\x18\x01 \x02(\t\x12\x13\n\x0b\x64omain_type\x18\x02 \x02(\x05\"k\n\x10KeywordsInDomain\x12\x10\n\x08keywords\x18\x01 \x03(\t\x12\x45\n\x06\x64omain\x18\x02 \x02(\x0b\x32\x35.com.gftchina.common.calcProtocol.idMapping.DomainDef\"k\n\x19ReqKeywordsDomainMappings\x12N\n\x08mappings\x18\x01 \x03(\x0b\x32<.com.gftchina.common.calcProtocol.idMapping.KeywordsInDomain\"*\n\nKeywordMap\x12\x0f\n\x07keyword\x18\x01 \x02(\t\x12\x0b\n\x03gid\x18\x02 \x02(\t\"\xac\x01\n\x19SingleDomainMappingResult\x12H\n\x08mappings\x18\x01 \x03(\x0b\x32\x36.com.gftchina.common.calcProtocol.idMapping.KeywordMap\x12\x45\n\x06\x64omain\x18\x02 \x02(\x0b\x32\x35.com.gftchina.common.calcProtocol.idMapping.DomainDef\"r\n\x18RespDomainMappingResults\x12V\n\x07results\x18\x01 \x03(\x0b\x32\x45.com.gftchina.common.calcProtocol.idMapping.SingleDomainMappingResult')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DOMAINDEF = _descriptor.Descriptor(
  name='DomainDef',
  full_name='com.gftchina.common.calcProtocol.idMapping.DomainDef',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='domain', full_name='com.gftchina.common.calcProtocol.idMapping.DomainDef.domain', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='domain_type', full_name='com.gftchina.common.calcProtocol.idMapping.DomainDef.domain_type', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=111,
)


_KEYWORDSINDOMAIN = _descriptor.Descriptor(
  name='KeywordsInDomain',
  full_name='com.gftchina.common.calcProtocol.idMapping.KeywordsInDomain',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='keywords', full_name='com.gftchina.common.calcProtocol.idMapping.KeywordsInDomain.keywords', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='domain', full_name='com.gftchina.common.calcProtocol.idMapping.KeywordsInDomain.domain', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=220,
)


_REQKEYWORDSDOMAINMAPPINGS = _descriptor.Descriptor(
  name='ReqKeywordsDomainMappings',
  full_name='com.gftchina.common.calcProtocol.idMapping.ReqKeywordsDomainMappings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mappings', full_name='com.gftchina.common.calcProtocol.idMapping.ReqKeywordsDomainMappings.mappings', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=222,
  serialized_end=329,
)


_KEYWORDMAP = _descriptor.Descriptor(
  name='KeywordMap',
  full_name='com.gftchina.common.calcProtocol.idMapping.KeywordMap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='keyword', full_name='com.gftchina.common.calcProtocol.idMapping.KeywordMap.keyword', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gid', full_name='com.gftchina.common.calcProtocol.idMapping.KeywordMap.gid', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=331,
  serialized_end=373,
)


_SINGLEDOMAINMAPPINGRESULT = _descriptor.Descriptor(
  name='SingleDomainMappingResult',
  full_name='com.gftchina.common.calcProtocol.idMapping.SingleDomainMappingResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mappings', full_name='com.gftchina.common.calcProtocol.idMapping.SingleDomainMappingResult.mappings', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='domain', full_name='com.gftchina.common.calcProtocol.idMapping.SingleDomainMappingResult.domain', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=376,
  serialized_end=548,
)


_RESPDOMAINMAPPINGRESULTS = _descriptor.Descriptor(
  name='RespDomainMappingResults',
  full_name='com.gftchina.common.calcProtocol.idMapping.RespDomainMappingResults',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='results', full_name='com.gftchina.common.calcProtocol.idMapping.RespDomainMappingResults.results', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=550,
  serialized_end=664,
)

_KEYWORDSINDOMAIN.fields_by_name['domain'].message_type = _DOMAINDEF
_REQKEYWORDSDOMAINMAPPINGS.fields_by_name['mappings'].message_type = _KEYWORDSINDOMAIN
_SINGLEDOMAINMAPPINGRESULT.fields_by_name['mappings'].message_type = _KEYWORDMAP
_SINGLEDOMAINMAPPINGRESULT.fields_by_name['domain'].message_type = _DOMAINDEF
_RESPDOMAINMAPPINGRESULTS.fields_by_name['results'].message_type = _SINGLEDOMAINMAPPINGRESULT
DESCRIPTOR.message_types_by_name['DomainDef'] = _DOMAINDEF
DESCRIPTOR.message_types_by_name['KeywordsInDomain'] = _KEYWORDSINDOMAIN
DESCRIPTOR.message_types_by_name['ReqKeywordsDomainMappings'] = _REQKEYWORDSDOMAINMAPPINGS
DESCRIPTOR.message_types_by_name['KeywordMap'] = _KEYWORDMAP
DESCRIPTOR.message_types_by_name['SingleDomainMappingResult'] = _SINGLEDOMAINMAPPINGRESULT
DESCRIPTOR.message_types_by_name['RespDomainMappingResults'] = _RESPDOMAINMAPPINGRESULTS

DomainDef = _reflection.GeneratedProtocolMessageType('DomainDef', (_message.Message,), dict(
  DESCRIPTOR = _DOMAINDEF,
  __module__ = 'idMapping_pb2'
  # @@protoc_insertion_point(class_scope:com.gftchina.common.calcProtocol.idMapping.DomainDef)
  ))
_sym_db.RegisterMessage(DomainDef)

KeywordsInDomain = _reflection.GeneratedProtocolMessageType('KeywordsInDomain', (_message.Message,), dict(
  DESCRIPTOR = _KEYWORDSINDOMAIN,
  __module__ = 'idMapping_pb2'
  # @@protoc_insertion_point(class_scope:com.gftchina.common.calcProtocol.idMapping.KeywordsInDomain)
  ))
_sym_db.RegisterMessage(KeywordsInDomain)

ReqKeywordsDomainMappings = _reflection.GeneratedProtocolMessageType('ReqKeywordsDomainMappings', (_message.Message,), dict(
  DESCRIPTOR = _REQKEYWORDSDOMAINMAPPINGS,
  __module__ = 'idMapping_pb2'
  # @@protoc_insertion_point(class_scope:com.gftchina.common.calcProtocol.idMapping.ReqKeywordsDomainMappings)
  ))
_sym_db.RegisterMessage(ReqKeywordsDomainMappings)

KeywordMap = _reflection.GeneratedProtocolMessageType('KeywordMap', (_message.Message,), dict(
  DESCRIPTOR = _KEYWORDMAP,
  __module__ = 'idMapping_pb2'
  # @@protoc_insertion_point(class_scope:com.gftchina.common.calcProtocol.idMapping.KeywordMap)
  ))
_sym_db.RegisterMessage(KeywordMap)

SingleDomainMappingResult = _reflection.GeneratedProtocolMessageType('SingleDomainMappingResult', (_message.Message,), dict(
  DESCRIPTOR = _SINGLEDOMAINMAPPINGRESULT,
  __module__ = 'idMapping_pb2'
  # @@protoc_insertion_point(class_scope:com.gftchina.common.calcProtocol.idMapping.SingleDomainMappingResult)
  ))
_sym_db.RegisterMessage(SingleDomainMappingResult)

RespDomainMappingResults = _reflection.GeneratedProtocolMessageType('RespDomainMappingResults', (_message.Message,), dict(
  DESCRIPTOR = _RESPDOMAINMAPPINGRESULTS,
  __module__ = 'idMapping_pb2'
  # @@protoc_insertion_point(class_scope:com.gftchina.common.calcProtocol.idMapping.RespDomainMappingResults)
  ))
_sym_db.RegisterMessage(RespDomainMappingResults)


# @@protoc_insertion_point(module_scope)
