# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: policyWindow.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2
from . import skill_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='policyWindow.proto',
  package='com.gftchina.common.persistence.policyWindow',
  serialized_pb=_b('\n\x12policyWindow.proto\x12,com.gftchina.common.persistence.policyWindow\x1a\x0c\x63ommon.proto\x1a\x0bskill.proto\"E\n\x03Row\x12>\n\x05\x63\x65lls\x18\x01 \x03(\x0b\x32/.com.gftchina.common.persistence.common.ColInfo\"\xa8\x01\n\x12StateVariableTable\x12\n\n\x02id\x18\x01 \x02(\t\x12\x45\n\ncolDefines\x18\x02 \x03(\x0b\x32\x31.com.gftchina.common.persistence.common.ColumnDef\x12?\n\x04rows\x18\x03 \x03(\x0b\x32\x31.com.gftchina.common.persistence.policyWindow.Row\"g\n\x0e\x41\x63tionSpaceRow\x12\x15\n\rsvtRowIndices\x18\x01 \x03(\x05\x12>\n\x03row\x18\x02 \x02(\x0b\x32\x31.com.gftchina.common.persistence.policyWindow.Row\"\xa5\x01\n\x10\x41\x63tionSpaceTable\x12\x45\n\ncolDefines\x18\x01 \x03(\x0b\x32\x31.com.gftchina.common.persistence.common.ColumnDef\x12J\n\x04rows\x18\x02 \x03(\x0b\x32<.com.gftchina.common.persistence.policyWindow.ActionSpaceRow\"|\n\x0eSVTJoinRequest\x12\x10\n\x08newSVTId\x18\x01 \x02(\t\x12X\n\x10\x61\x63tionSpaceTable\x18\x02 \x02(\x0b\x32>.com.gftchina.common.persistence.policyWindow.ActionSpaceTable\"7\n\x0eSkillParaInSVT\x12\x10\n\x08paraName\x18\x01 \x02(\t\x12\x13\n\x0b\x63olumnIndex\x18\x02 \x02(\x05\"\xda\x01\n\rSVTRunRequest\x12\x10\n\x08skillGid\x18\x01 \x02(\t\x12M\n\rparasOutOfSVT\x18\x02 \x01(\x0b\x32\x36.com.gftchina.common.persistence.skill.SkillParameters\x12P\n\nparasInSVT\x18\x03 \x03(\x0b\x32<.com.gftchina.common.persistence.policyWindow.SkillParaInSVT\x12\x16\n\x0erowsToRunSkill\x18\x04 \x03(\x05')
  ,
  dependencies=[common_pb2.DESCRIPTOR,skill_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ROW = _descriptor.Descriptor(
  name='Row',
  full_name='com.gftchina.common.persistence.policyWindow.Row',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cells', full_name='com.gftchina.common.persistence.policyWindow.Row.cells', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=164,
)


_STATEVARIABLETABLE = _descriptor.Descriptor(
  name='StateVariableTable',
  full_name='com.gftchina.common.persistence.policyWindow.StateVariableTable',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='com.gftchina.common.persistence.policyWindow.StateVariableTable.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='colDefines', full_name='com.gftchina.common.persistence.policyWindow.StateVariableTable.colDefines', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rows', full_name='com.gftchina.common.persistence.policyWindow.StateVariableTable.rows', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=335,
)


_ACTIONSPACEROW = _descriptor.Descriptor(
  name='ActionSpaceRow',
  full_name='com.gftchina.common.persistence.policyWindow.ActionSpaceRow',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='svtRowIndices', full_name='com.gftchina.common.persistence.policyWindow.ActionSpaceRow.svtRowIndices', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='row', full_name='com.gftchina.common.persistence.policyWindow.ActionSpaceRow.row', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=337,
  serialized_end=440,
)


_ACTIONSPACETABLE = _descriptor.Descriptor(
  name='ActionSpaceTable',
  full_name='com.gftchina.common.persistence.policyWindow.ActionSpaceTable',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='colDefines', full_name='com.gftchina.common.persistence.policyWindow.ActionSpaceTable.colDefines', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rows', full_name='com.gftchina.common.persistence.policyWindow.ActionSpaceTable.rows', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=443,
  serialized_end=608,
)


_SVTJOINREQUEST = _descriptor.Descriptor(
  name='SVTJoinRequest',
  full_name='com.gftchina.common.persistence.policyWindow.SVTJoinRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='newSVTId', full_name='com.gftchina.common.persistence.policyWindow.SVTJoinRequest.newSVTId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='actionSpaceTable', full_name='com.gftchina.common.persistence.policyWindow.SVTJoinRequest.actionSpaceTable', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=610,
  serialized_end=734,
)


_SKILLPARAINSVT = _descriptor.Descriptor(
  name='SkillParaInSVT',
  full_name='com.gftchina.common.persistence.policyWindow.SkillParaInSVT',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='paraName', full_name='com.gftchina.common.persistence.policyWindow.SkillParaInSVT.paraName', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='columnIndex', full_name='com.gftchina.common.persistence.policyWindow.SkillParaInSVT.columnIndex', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=736,
  serialized_end=791,
)


_SVTRUNREQUEST = _descriptor.Descriptor(
  name='SVTRunRequest',
  full_name='com.gftchina.common.persistence.policyWindow.SVTRunRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='skillGid', full_name='com.gftchina.common.persistence.policyWindow.SVTRunRequest.skillGid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='parasOutOfSVT', full_name='com.gftchina.common.persistence.policyWindow.SVTRunRequest.parasOutOfSVT', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='parasInSVT', full_name='com.gftchina.common.persistence.policyWindow.SVTRunRequest.parasInSVT', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rowsToRunSkill', full_name='com.gftchina.common.persistence.policyWindow.SVTRunRequest.rowsToRunSkill', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=794,
  serialized_end=1012,
)

_ROW.fields_by_name['cells'].message_type = common_pb2._COLINFO
_STATEVARIABLETABLE.fields_by_name['colDefines'].message_type = common_pb2._COLUMNDEF
_STATEVARIABLETABLE.fields_by_name['rows'].message_type = _ROW
_ACTIONSPACEROW.fields_by_name['row'].message_type = _ROW
_ACTIONSPACETABLE.fields_by_name['colDefines'].message_type = common_pb2._COLUMNDEF
_ACTIONSPACETABLE.fields_by_name['rows'].message_type = _ACTIONSPACEROW
_SVTJOINREQUEST.fields_by_name['actionSpaceTable'].message_type = _ACTIONSPACETABLE
_SVTRUNREQUEST.fields_by_name['parasOutOfSVT'].message_type = skill_pb2._SKILLPARAMETERS
_SVTRUNREQUEST.fields_by_name['parasInSVT'].message_type = _SKILLPARAINSVT
DESCRIPTOR.message_types_by_name['Row'] = _ROW
DESCRIPTOR.message_types_by_name['StateVariableTable'] = _STATEVARIABLETABLE
DESCRIPTOR.message_types_by_name['ActionSpaceRow'] = _ACTIONSPACEROW
DESCRIPTOR.message_types_by_name['ActionSpaceTable'] = _ACTIONSPACETABLE
DESCRIPTOR.message_types_by_name['SVTJoinRequest'] = _SVTJOINREQUEST
DESCRIPTOR.message_types_by_name['SkillParaInSVT'] = _SKILLPARAINSVT
DESCRIPTOR.message_types_by_name['SVTRunRequest'] = _SVTRUNREQUEST

Row = _reflection.GeneratedProtocolMessageType('Row', (_message.Message,), dict(
  DESCRIPTOR = _ROW,
  __module__ = 'policyWindow_pb2'
  # @@protoc_insertion_point(class_scope:com.gftchina.common.persistence.policyWindow.Row)
  ))
_sym_db.RegisterMessage(Row)

StateVariableTable = _reflection.GeneratedProtocolMessageType('StateVariableTable', (_message.Message,), dict(
  DESCRIPTOR = _STATEVARIABLETABLE,
  __module__ = 'policyWindow_pb2'
  # @@protoc_insertion_point(class_scope:com.gftchina.common.persistence.policyWindow.StateVariableTable)
  ))
_sym_db.RegisterMessage(StateVariableTable)

ActionSpaceRow = _reflection.GeneratedProtocolMessageType('ActionSpaceRow', (_message.Message,), dict(
  DESCRIPTOR = _ACTIONSPACEROW,
  __module__ = 'policyWindow_pb2'
  # @@protoc_insertion_point(class_scope:com.gftchina.common.persistence.policyWindow.ActionSpaceRow)
  ))
_sym_db.RegisterMessage(ActionSpaceRow)

ActionSpaceTable = _reflection.GeneratedProtocolMessageType('ActionSpaceTable', (_message.Message,), dict(
  DESCRIPTOR = _ACTIONSPACETABLE,
  __module__ = 'policyWindow_pb2'
  # @@protoc_insertion_point(class_scope:com.gftchina.common.persistence.policyWindow.ActionSpaceTable)
  ))
_sym_db.RegisterMessage(ActionSpaceTable)

SVTJoinRequest = _reflection.GeneratedProtocolMessageType('SVTJoinRequest', (_message.Message,), dict(
  DESCRIPTOR = _SVTJOINREQUEST,
  __module__ = 'policyWindow_pb2'
  # @@protoc_insertion_point(class_scope:com.gftchina.common.persistence.policyWindow.SVTJoinRequest)
  ))
_sym_db.RegisterMessage(SVTJoinRequest)

SkillParaInSVT = _reflection.GeneratedProtocolMessageType('SkillParaInSVT', (_message.Message,), dict(
  DESCRIPTOR = _SKILLPARAINSVT,
  __module__ = 'policyWindow_pb2'
  # @@protoc_insertion_point(class_scope:com.gftchina.common.persistence.policyWindow.SkillParaInSVT)
  ))
_sym_db.RegisterMessage(SkillParaInSVT)

SVTRunRequest = _reflection.GeneratedProtocolMessageType('SVTRunRequest', (_message.Message,), dict(
  DESCRIPTOR = _SVTRUNREQUEST,
  __module__ = 'policyWindow_pb2'
  # @@protoc_insertion_point(class_scope:com.gftchina.common.persistence.policyWindow.SVTRunRequest)
  ))
_sym_db.RegisterMessage(SVTRunRequest)


# @@protoc_insertion_point(module_scope)
