# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qCoin.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='qCoin.proto',
  package='com.gftchina.common.persistence.qcoin',
  serialized_pb=_b('\n\x0bqCoin.proto\x12%com.gftchina.common.persistence.qcoin\"A\n\x04Item\x12\x0c\n\x04type\x18\x01 \x02(\x05\x12\x0b\n\x03val\x18\x02 \x02(\x03\x12\r\n\x05mTime\x18\x03 \x02(\x03\x12\x0f\n\x07\x63ounter\x18\x04 \x01(\x03\"~\n\x07\x41\x63\x63ount\x12\r\n\x05usrId\x18\x01 \x01(\t\x12\r\n\x05qCoin\x18\x02 \x02(\x03\x12\x15\n\rlastLoginTime\x18\x03 \x01(\x03\x12>\n\tstatistcs\x18\x04 \x03(\x0b\x32+.com.gftchina.common.persistence.qcoin.Item\"\x94\x01\n\x0bTransaction\x12\x0e\n\x06userId\x18\x01 \x01(\t\x12\x10\n\x08qCoinNow\x18\x02 \x02(\x03\x12:\n\x05\x64\x65lta\x18\x03 \x01(\x0b\x32+.com.gftchina.common.persistence.qcoin.Item\x12\x15\n\rcounterpartId\x18\x04 \x01(\t\x12\x10\n\x08rollback\x18\x05 \x01(\x08')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ITEM = _descriptor.Descriptor(
  name='Item',
  full_name='com.gftchina.common.persistence.qcoin.Item',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='com.gftchina.common.persistence.qcoin.Item.type', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='val', full_name='com.gftchina.common.persistence.qcoin.Item.val', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mTime', full_name='com.gftchina.common.persistence.qcoin.Item.mTime', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='counter', full_name='com.gftchina.common.persistence.qcoin.Item.counter', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=119,
)


_ACCOUNT = _descriptor.Descriptor(
  name='Account',
  full_name='com.gftchina.common.persistence.qcoin.Account',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='usrId', full_name='com.gftchina.common.persistence.qcoin.Account.usrId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='qCoin', full_name='com.gftchina.common.persistence.qcoin.Account.qCoin', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lastLoginTime', full_name='com.gftchina.common.persistence.qcoin.Account.lastLoginTime', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='statistcs', full_name='com.gftchina.common.persistence.qcoin.Account.statistcs', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=247,
)


_TRANSACTION = _descriptor.Descriptor(
  name='Transaction',
  full_name='com.gftchina.common.persistence.qcoin.Transaction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='com.gftchina.common.persistence.qcoin.Transaction.userId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='qCoinNow', full_name='com.gftchina.common.persistence.qcoin.Transaction.qCoinNow', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='delta', full_name='com.gftchina.common.persistence.qcoin.Transaction.delta', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='counterpartId', full_name='com.gftchina.common.persistence.qcoin.Transaction.counterpartId', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rollback', full_name='com.gftchina.common.persistence.qcoin.Transaction.rollback', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=250,
  serialized_end=398,
)

_ACCOUNT.fields_by_name['statistcs'].message_type = _ITEM
_TRANSACTION.fields_by_name['delta'].message_type = _ITEM
DESCRIPTOR.message_types_by_name['Item'] = _ITEM
DESCRIPTOR.message_types_by_name['Account'] = _ACCOUNT
DESCRIPTOR.message_types_by_name['Transaction'] = _TRANSACTION

Item = _reflection.GeneratedProtocolMessageType('Item', (_message.Message,), dict(
  DESCRIPTOR = _ITEM,
  __module__ = 'qCoin_pb2'
  # @@protoc_insertion_point(class_scope:com.gftchina.common.persistence.qcoin.Item)
  ))
_sym_db.RegisterMessage(Item)

Account = _reflection.GeneratedProtocolMessageType('Account', (_message.Message,), dict(
  DESCRIPTOR = _ACCOUNT,
  __module__ = 'qCoin_pb2'
  # @@protoc_insertion_point(class_scope:com.gftchina.common.persistence.qcoin.Account)
  ))
_sym_db.RegisterMessage(Account)

Transaction = _reflection.GeneratedProtocolMessageType('Transaction', (_message.Message,), dict(
  DESCRIPTOR = _TRANSACTION,
  __module__ = 'qCoin_pb2'
  # @@protoc_insertion_point(class_scope:com.gftchina.common.persistence.qcoin.Transaction)
  ))
_sym_db.RegisterMessage(Transaction)


# @@protoc_insertion_point(module_scope)
