# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: query.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import dbms_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='query.proto',
  package='com.gftchina.common.persistence.query',
  serialized_pb=_b('\n\x0bquery.proto\x12%com.gftchina.common.persistence.query\x1a\ndbms.proto\"s\n\x1bQueryPersistentRecordSchema\x12\x0b\n\x03gid\x18\x01 \x02(\t\x12G\n\x04type\x18\x02 \x01(\x0e\x32\x35.com.gftchina.common.persistence.query.PersistentType:\x02\x46I\"\x9d\x01\n\x16PersistentRecordSchema\x12>\n\x06schema\x18\x01 \x03(\x0b\x32..com.gftchina.common.persistence.dbms.OneField\x12\x43\n\x04type\x18\x02 \x01(\x0e\x32\x35.com.gftchina.common.persistence.query.PersistentType\"\xd3\x02\n\x19QueryPersistentRecordInfo\x12H\n\nconditions\x18\x01 \x03(\x0b\x32\x34.com.gftchina.common.persistence.dbms.FieldCondition\x12\x43\n\x04type\x18\x02 \x01(\x0e\x32\x35.com.gftchina.common.persistence.query.PersistentType\x12\x10\n\x05limit\x18\x04 \x01(\r:\x01\x31\x12\x41\n\tselection\x18\x05 \x03(\x0b\x32..com.gftchina.common.persistence.dbms.OneField\x12\x12\n\nsessionGid\x18\x07 \x01(\t\x12\x11\n\taggregate\x18\x08 \x01(\x08\x12\x11\n\tqueryData\x18\t \x01(\x08\x12\x18\n\x10\x61ggreationChoice\x18\n \x01(\x05*\'\n\x0ePersistentType\x12\x06\n\x02\x46I\x10\x01\x12\r\n\tWorkspace\x10\x02*I\n\x0f\x41ggregationType\x12\t\n\x05\x43ount\x10\x01\x12\x07\n\x03Max\x10\x02\x12\x07\n\x03Min\x10\x04\x12\x07\n\x03\x41vg\x10\x08\x12\x07\n\x03Sum\x10\x10\x12\x07\n\x03\x41ll\x10\x1f')
  ,
  dependencies=[dbms_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_PERSISTENTTYPE = _descriptor.EnumDescriptor(
  name='PersistentType',
  full_name='com.gftchina.common.persistence.query.PersistentType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FI', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Workspace', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=685,
  serialized_end=724,
)
_sym_db.RegisterEnumDescriptor(_PERSISTENTTYPE)

PersistentType = enum_type_wrapper.EnumTypeWrapper(_PERSISTENTTYPE)
_AGGREGATIONTYPE = _descriptor.EnumDescriptor(
  name='AggregationType',
  full_name='com.gftchina.common.persistence.query.AggregationType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Count', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Max', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Min', index=2, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Avg', index=3, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Sum', index=4, number=16,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='All', index=5, number=31,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=726,
  serialized_end=799,
)
_sym_db.RegisterEnumDescriptor(_AGGREGATIONTYPE)

AggregationType = enum_type_wrapper.EnumTypeWrapper(_AGGREGATIONTYPE)
FI = 1
Workspace = 2
Count = 1
Max = 2
Min = 4
Avg = 8
Sum = 16
All = 31



_QUERYPERSISTENTRECORDSCHEMA = _descriptor.Descriptor(
  name='QueryPersistentRecordSchema',
  full_name='com.gftchina.common.persistence.query.QueryPersistentRecordSchema',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gid', full_name='com.gftchina.common.persistence.query.QueryPersistentRecordSchema.gid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='com.gftchina.common.persistence.query.QueryPersistentRecordSchema.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=181,
)


_PERSISTENTRECORDSCHEMA = _descriptor.Descriptor(
  name='PersistentRecordSchema',
  full_name='com.gftchina.common.persistence.query.PersistentRecordSchema',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='schema', full_name='com.gftchina.common.persistence.query.PersistentRecordSchema.schema', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='com.gftchina.common.persistence.query.PersistentRecordSchema.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=184,
  serialized_end=341,
)


_QUERYPERSISTENTRECORDINFO = _descriptor.Descriptor(
  name='QueryPersistentRecordInfo',
  full_name='com.gftchina.common.persistence.query.QueryPersistentRecordInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='conditions', full_name='com.gftchina.common.persistence.query.QueryPersistentRecordInfo.conditions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='com.gftchina.common.persistence.query.QueryPersistentRecordInfo.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='limit', full_name='com.gftchina.common.persistence.query.QueryPersistentRecordInfo.limit', index=2,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='selection', full_name='com.gftchina.common.persistence.query.QueryPersistentRecordInfo.selection', index=3,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sessionGid', full_name='com.gftchina.common.persistence.query.QueryPersistentRecordInfo.sessionGid', index=4,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='aggregate', full_name='com.gftchina.common.persistence.query.QueryPersistentRecordInfo.aggregate', index=5,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='queryData', full_name='com.gftchina.common.persistence.query.QueryPersistentRecordInfo.queryData', index=6,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='aggreationChoice', full_name='com.gftchina.common.persistence.query.QueryPersistentRecordInfo.aggreationChoice', index=7,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=344,
  serialized_end=683,
)

_QUERYPERSISTENTRECORDSCHEMA.fields_by_name['type'].enum_type = _PERSISTENTTYPE
_PERSISTENTRECORDSCHEMA.fields_by_name['schema'].message_type = dbms_pb2._ONEFIELD
_PERSISTENTRECORDSCHEMA.fields_by_name['type'].enum_type = _PERSISTENTTYPE
_QUERYPERSISTENTRECORDINFO.fields_by_name['conditions'].message_type = dbms_pb2._FIELDCONDITION
_QUERYPERSISTENTRECORDINFO.fields_by_name['type'].enum_type = _PERSISTENTTYPE
_QUERYPERSISTENTRECORDINFO.fields_by_name['selection'].message_type = dbms_pb2._ONEFIELD
DESCRIPTOR.message_types_by_name['QueryPersistentRecordSchema'] = _QUERYPERSISTENTRECORDSCHEMA
DESCRIPTOR.message_types_by_name['PersistentRecordSchema'] = _PERSISTENTRECORDSCHEMA
DESCRIPTOR.message_types_by_name['QueryPersistentRecordInfo'] = _QUERYPERSISTENTRECORDINFO
DESCRIPTOR.enum_types_by_name['PersistentType'] = _PERSISTENTTYPE
DESCRIPTOR.enum_types_by_name['AggregationType'] = _AGGREGATIONTYPE

QueryPersistentRecordSchema = _reflection.GeneratedProtocolMessageType('QueryPersistentRecordSchema', (_message.Message,), dict(
  DESCRIPTOR = _QUERYPERSISTENTRECORDSCHEMA,
  __module__ = 'query_pb2'
  # @@protoc_insertion_point(class_scope:com.gftchina.common.persistence.query.QueryPersistentRecordSchema)
  ))
_sym_db.RegisterMessage(QueryPersistentRecordSchema)

PersistentRecordSchema = _reflection.GeneratedProtocolMessageType('PersistentRecordSchema', (_message.Message,), dict(
  DESCRIPTOR = _PERSISTENTRECORDSCHEMA,
  __module__ = 'query_pb2'
  # @@protoc_insertion_point(class_scope:com.gftchina.common.persistence.query.PersistentRecordSchema)
  ))
_sym_db.RegisterMessage(PersistentRecordSchema)

QueryPersistentRecordInfo = _reflection.GeneratedProtocolMessageType('QueryPersistentRecordInfo', (_message.Message,), dict(
  DESCRIPTOR = _QUERYPERSISTENTRECORDINFO,
  __module__ = 'query_pb2'
  # @@protoc_insertion_point(class_scope:com.gftchina.common.persistence.query.QueryPersistentRecordInfo)
  ))
_sym_db.RegisterMessage(QueryPersistentRecordInfo)


# @@protoc_insertion_point(module_scope)
