# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vq2Neo4j.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='vq2Neo4j.proto',
  package='com.gftchina.common.persistence.serviceInternal',
  serialized_pb=_b('\n\x0evq2Neo4j.proto\x12/com.gftchina.common.persistence.serviceInternal\"-\n\x0cRespNeo4j2VQ\x12\x0c\n\x04\x62ody\x18\x01 \x02(\x0c\x12\x0f\n\x07warning\x18\x02 \x01(\x0c\"B\n\x0bUserDetails\x12\x0e\n\x06userId\x18\x01 \x02(\t\x12\x11\n\tloginName\x18\x02 \x02(\t\x12\x10\n\x08userName\x18\x03 \x02(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_RESPNEO4J2VQ = _descriptor.Descriptor(
  name='RespNeo4j2VQ',
  full_name='com.gftchina.common.persistence.serviceInternal.RespNeo4j2VQ',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='body', full_name='com.gftchina.common.persistence.serviceInternal.RespNeo4j2VQ.body', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='warning', full_name='com.gftchina.common.persistence.serviceInternal.RespNeo4j2VQ.warning', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=112,
)


_USERDETAILS = _descriptor.Descriptor(
  name='UserDetails',
  full_name='com.gftchina.common.persistence.serviceInternal.UserDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='com.gftchina.common.persistence.serviceInternal.UserDetails.userId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='loginName', full_name='com.gftchina.common.persistence.serviceInternal.UserDetails.loginName', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='userName', full_name='com.gftchina.common.persistence.serviceInternal.UserDetails.userName', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=180,
)

DESCRIPTOR.message_types_by_name['RespNeo4j2VQ'] = _RESPNEO4J2VQ
DESCRIPTOR.message_types_by_name['UserDetails'] = _USERDETAILS

RespNeo4j2VQ = _reflection.GeneratedProtocolMessageType('RespNeo4j2VQ', (_message.Message,), dict(
  DESCRIPTOR = _RESPNEO4J2VQ,
  __module__ = 'vq2Neo4j_pb2'
  # @@protoc_insertion_point(class_scope:com.gftchina.common.persistence.serviceInternal.RespNeo4j2VQ)
  ))
_sym_db.RegisterMessage(RespNeo4j2VQ)

UserDetails = _reflection.GeneratedProtocolMessageType('UserDetails', (_message.Message,), dict(
  DESCRIPTOR = _USERDETAILS,
  __module__ = 'vq2Neo4j_pb2'
  # @@protoc_insertion_point(class_scope:com.gftchina.common.persistence.serviceInternal.UserDetails)
  ))
_sym_db.RegisterMessage(UserDetails)


# @@protoc_insertion_point(module_scope)
